# Generated by Django 4.2.25 on 2025-10-14 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='memebers',
            new_name='members',
        ),
    ]
